---
linear_feedback_controller:
  ros__parameters:
    type: linear_feedback_controller/LinearFeedbackController
    moving_joint_names: [arm_right_1_joint, arm_right_2_joint, arm_right_3_joint, arm_right_4_joint,
      arm_right_5_joint, arm_right_6_joint, arm_right_7_joint]
    arm_right_1_joint:
      p: 50.0
      d: 0.5
    arm_right_2_joint:
      p: 50.0
      d: 0.5
    arm_right_3_joint:
      p: 50.0
      d: 0.5
    arm_right_4_joint:
      p: 50.0
      d: 0.5
    arm_right_5_joint:
      p: 10.0
      d: 0.3
    arm_right_6_joint:
      p: 5.0
      d: 0.3
    arm_right_7_joint:
      p: 5.0
      d: 0.0
    chainable_controller:
      command_interfaces: [arm_right_1_joint/force,
        arm_right_2_joint/force, arm_right_3_joint/force,
        arm_right_4_joint/force, arm_right_5_joint/force,
        arm_right_6_joint/force, arm_right_7_joint/force]
      reference_prefix: ''
    joint_velocity_filter_coefficient: 0.9
    pd_to_lf_transition_duration: 0.1
    remove_gravity_compensation_effort: false
    robot_has_free_flyer: false
