---
deburring_orchestrator:
  ros__parameters:
    mpc_input_topic_name: /agimus_pytroller/mpc_input
    buffer_size_topic_name: /agimus_pytroller/buffer_size
    update_frequency: 0.02
    buffer_size: 50
    pylone_used_handles: [pylone/hole_back_left_2, pylone/hole_back_left_3, pylone/hole_back_left_1]
    ee_frame_name: fer_hand
    gripper_name: panda_gripper
    w_q: [1.0]
    w_qdot: [0.1]
    w_qddot: [0.0001]
    w_robot_effort: [0.001]
    w_pose: [0.1]
    world_frame: fer_link0
    pylone_frame: pylone_link
