#!/usr/bin/env python3

import rclpy
from agimus_demo_07_deburring.orchestrator import Orchestrator


def main():
    rclpy.init()
    o = Orchestrator()  # Instantiate your ROS 2 node

    # q_init -> f_01 (pregrasp) -> f_12 (move down) -> 0-0_21 (retract) -> repeat

    print("\nROS 2 Node initialized. Starting IPython shell...\n")

    try:
        import IPython

        # "panda/panda_gripper > pylone/hole_02 | f_01": 8, -- pregrasp
        # "panda/panda_gripper > pylone/hole_02 | f_12": 8, -- entering the hole

        o.create_viewer()
        o.update_environment()
        o.update_initial_configuration()
        o.perform_motion()
        # print(o._hpp_interface.cg.edges)
        # q_final = o._hpp_interface.sample_state_on_transition_target(
        #     q_from=o._hpp_interface._q_init,
        #     transition="panda/panda_gripper > pylone/hole_03 | f",
        #     max_iter=100,
        # )
        # o._hpp_interface.ps.addGoalConfig(q_final.copy())

        # q_final = o._hpp_interface.sample_state_on_transition_target(
        #     q_from=o._hpp_interface._q_init,
        #     transition="panda/panda_gripper > pylone/hole_02 | f",
        #     max_iter=100,
        # )
        # o._hpp_interface.ps.addGoalConfig(q_final.copy())
        # o.solve()
        # o.play_path()

        IPython.embed()  # Start an interactive IPython shell
    except ImportError:
        import code

        code.interact(local=locals())  # Fallback to standard Python shell

    rclpy.shutdown()


if __name__ == "__main__":
    main()
