---
# handles_configurations.yaml
# Association grippers <-> handles avec placement de la barre
# Format placement : [x, y, z, qx, qy, qz, qw] dans le repère monde

grippers:
  tiago_pro/left:
    handles:
    - name: reinforcement_bar/left
      placement: [0., 0.1, 0.25, 0.0, 0.0, -0.707, 0.707]

  tiago_pro/right:
    handles:
    - name: reinforcement_bar/right
      placement: [0., -0.1, 0.25, 0.0, 0.0, -0.707, 0.707]
