#!/usr/bin/env python3

import rclpy
from agimus_demo_06_regrasp.image_saver import ImageSaver


def main():
    rclpy.init(args=None)
    image_saver = ImageSaver()
    rclpy.spin(image_saver)
    image_saver.destroy_node()
    rclpy.shutdown()


if __name__ == "__main__":
    main()
