---
# MPC parameters for the TIAGo Pro deburring demo (fixed base, right arm only).
#
# State space: nq = 7, nv = 7 (right arm joints only)

agimus_controller_node:
  ros__parameters:
    rate: 100.0
    free_flyer: false
    ocp:
      dt: 0.01
      horizon_size: 19
      dt_factor_n_seq:
        n_steps: [5, 5, 5, 4]
        factors: [1, 2, 4, 8]
      armature: [0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1]
      max_qp_iter: 50
      max_iter: 5
      activate_callback: false
      effector_frame_name: gripper_right_fingertip_left_link
      definition_yaml_file: package://agimus_demo_07_fixed_tiago_pro_deburring/config/ocp_definition_file.yaml
    robot_attachment_frame: universe
    collision_pairs_names: [cp_1]
    cp_1:
      first: arm_right_7_link_0
      second: arm_left_7_link_0
